# Generated by Django 4.2.23 on 2025-07-06 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('user', models.OneToOneField(help_text='Player represented on the leaderboard.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leaderboard_entry', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_score', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score achieved in this session.')),
                ('game_mode', models.CharField(help_text='Game mode or level identifier.', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='Player who played this session.', on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-score'], name='gamesession_score_idx'), models.Index(fields=['user'], name='gamesession_user_idx'), models.Index(fields=['game_mode'], name='gamesession_mode_idx')],
            },
        ),
    ]
